### ISSUE TITLE
v0.0.1 tracking

### ISSUE THREAD

**Issue by jonasteuwen** [NKI-AI/ahcore#7]
Required for version v0.0.1:

- [ ] Full documented example for the TIGER challenge (#6)
- [ ] Inference must use different manifest (#5)
- [ ] TiffWriter tracker must support tile skipping (#4)
- [ ] Multiple U-nets implemented
- [ ] Support for automatic hparam search
